import React, { useEffect, useState, useRef } from "react";
import Head from "next/head";
import Scene from "@/components/common/Scene";
import { useSelector, useDispatch } from "react-redux";
import s from "./Car.module.scss";
import { GetCars } from "@/actions/CarActions";
import { useRouter } from "next/router";
import Link from "next/link";
import gsap from "gsap";

const Car = () => {
  const index = useRouter().query.index;
  const { cars, loaded } = useSelector((store) => store.CarReducer);
  const descriptionRef = useRef();
  let car = cars.find((item) => item.id === Number(index));

  const dispatch = useDispatch();

  const handleClick = () => {
    gsap.fromTo(
      descriptionRef.current,
      {
        x: 1000,
      },
      {
        opacity: 1,
        x: 0,
      }
    );
  };

  const handleClose = () => {
    gsap.fromTo(
      descriptionRef.current,
      {
        x: 0,
      },
      {
        opacity: 0,
        x: 1000,
      }
    );
  };

  useEffect(() => {
    dispatch(GetCars());
  }, []);

  if (loaded === false) {
    return <div>loading</div>;
  }

  return (
    <>
      <Head>
        {car === undefined ? (
          <title>not found</title>
        ) : (
          <title>{car.name}</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={s.root}>
        <div className={s.scene_wrapper}>
          {car === undefined ? (
            <h1>404</h1>
          ) : (
            <>
              <div className={s.header}>
                <Link href={"/"}> HOME</Link>
                <button onClick={handleClick}>INFO</button>
              </div>
              <h1 className={s.title}>{car.name}</h1>
              <div className={s.description}>
                <div className={s.description_wrapper} ref={descriptionRef}>
                  <div className={s.close} onClick={handleClose}>
                    <img src="/close.svg" alt="close" />
                  </div>
                  <div className={s.description_item}>
                    <p className={s.description_item_title}> Цена: </p>
                    <p>{car.price} руб</p>
                  </div>
                  <div className={s.description_item}>
                    <p className={s.description_item_title}> Цвет: </p>
                    <p> {car.color} </p>
                  </div>

                  <div className={s.description_item}>
                    <p className={s.description_item_title}> Год выпуска: </p>
                    <p>{car.year} </p>
                  </div>

                  <div className={s.description_item}>
                    <p className={s.description_item_title}> Страна: </p>
                    <p> {car.country} </p>
                  </div>

                  <div className={s.description_item}>
                    <p className={s.description_item_title}> Кузов: </p>
                    <p> {car.body} </p>
                  </div>

                  <div className={s.description_item}>
                    <p className={s.description_item_title}>Лошадиные силы:</p>
                    <p> {car.hp} </p>
                  </div>

                  <div className={s.description_item}>
                    <p className={s.description_item_title}>Обьем двигателя:</p>
                    <p> {car.eng}</p>
                  </div>

                  <div className={s.description_item}>
                    <p className={s.description_item_title}> Описание: </p>
                    <div>{car.description}</div>
                  </div>
                </div>
              </div>
              <div className={s.scene}>
                <Scene color={car.color} orbit={true} />
              </div>
            </>
          )}
        </div>
      </div>
    </>
  );
};

export default Car;
