import Head from "next/head";
import Scene from "@/components/common/Scene";
import CloseIcon from "@/components/icons/Close";
import Link from "next/link";
import s from "./Car.module.scss";
import React from "react";

const Car = (props) => {
  const { car, loaded, descriptionRef } = props;

  const handleClick = useCallback(() => {
    gsap.fromTo(
      descriptionRef.current,
      {
        x: 1000,
      },
      {
        opacity: 1,
        x: 0,
      }
    );
  }, []);

  const handleClose = useCallback(() => {
    gsap.fromTo(
      descriptionRef.current,
      {
        x: 0,
      },
      {
        opacity: 0,
        x: 1000,
      }
    );
  }, []);

  if (loaded === false) {
    return <div>loading</div>;
  }

  return (
    <>
      <Head>
        {car === undefined ? (
          <title>not found</title>
        ) : (
          <title>{car.name}</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={s.root}>
        <div className={s.sceneWrapper}>
          {car === undefined ? (
            <h1>404</h1>
          ) : (
            <>
              <div className={s.header}>
                <Link href={"/"}> HOME</Link>
                <button onClick={handleClick}>INFO</button>
              </div>
              <h1 className={s.title}>{car.name}</h1>
              <div className={s.description}>
                <div className={s.descriptionWrapper} ref={descriptionRef}>
                  <div className={s.close} onClick={handleClose}>
                    <CloseIcon />
                  </div>
                  <div className={s.descriptionItem}>
                    <p className={s.descriptionItemTitle}> Цена: </p>
                    <p>{car.price} руб</p>
                  </div>
                  <div className={s.descriptionItem}>
                    <p className={s.descriptionItemTitle}> Цвет: </p>
                    <p> {car.color} </p>
                  </div>

                  <div className={s.descriptionItem}>
                    <p className={s.descriptionItemTitle}> Год выпуска: </p>
                    <p>{car.year} </p>
                  </div>

                  <div className={s.descriptionItem}>
                    <p className={s.descriptionItemTitle}> Страна: </p>
                    <p> {car.country} </p>
                  </div>

                  <div className={s.descriptionItem}>
                    <p className={s.descriptionItemTitle}> Кузов: </p>
                    <p> {car.body} </p>
                  </div>

                  <div className={s.descriptionItem}>
                    <p className={s.descriptionItemTitle}>Лошадиные силы:</p>
                    <p> {car.hp} </p>
                  </div>

                  <div className={s.descriptionItem}>
                    <p className={s.descriptionItemTitle}>Обьем двигателя:</p>
                    <p> {car.eng}</p>
                  </div>

                  <div className={s.descriptionItem}>
                    <p className={s.descriptionItemTitle}> Описание: </p>
                    <div>{car.description}</div>
                  </div>
                </div>
              </div>
              <div className={s.scene}>
                <Scene color={car.color} orbit={true} />
              </div>
            </>
          )}
        </div>
      </div>
    </>
  );
};

export default Car;
