import React, { useEffect } from "react";
import Head from "next/head";
import s from "./CarPage.module.scss";

import { useSelector, useDispatch } from "react-redux";
import { useRouter } from "next/router";
import { GetCars } from "@/actions/CarActions";

const CarPage = () => {
  const dispatch = useDispatch();
  const { cars } = useSelector((state) => state.CarReducer);
  const index = useRouter().query.index;

  const car = cars.find((item) => item.id === Number(index));
  useEffect(() => {
    dispatch(GetCars());
  }, []);

  return (
    <>
      <Head>
        {car === undefined ? (
          <title>not found</title>
        ) : (
          <title>{car.name}</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={s.root}>
        {car === undefined ? <h1>not found</h1> : <h1>{car.name}</h1>}
      </div>
    </>
  );
};

export default CarPage;
